name: YEETTheChat
version: ${project.version}
main: me.raimuakuna.yeetthechat.Yeetthechat
api-version: 1.15
authors: [cayoten (raimuakuna)]
description: A simple chat clearing plugin, but funny!
commands:
  yeetchat:
    description: Clear your chat!
    usage: /yeetchat
  ycreload:
    description: Reloads the plugin & config.
    usage: /ycreload